### ISSUE TITLE
App crashes with following stacktrace

### ISSUE THREAD

**Issue by shivamsingh** [passy/Android-DirectoryChooser#111]
Caused by: java.lang.IllegalArgumentException: You need to use a Theme.AppCompat theme (or descendant) with the design library.
                                                                           at android.support.design.widget.ThemeUtils.checkAppCompatTheme(ThemeUtils.java:36)
                                                                           at android.support.design.widget.AppBarLayout.<init>(AppBarLayout.java:151)
                                                                           at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143) 
                                                                           at com.nbsp.materialfilepicker.ui.FilePickerActivity.onCreate(FilePickerActivity.java:50) 
                                                                           at android.app.Activity.performCreate(Activity.java:6220) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2513) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2646) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:182) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                           at android.os.Looper.loop(Looper.java:194) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5763) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)

**Comment by passy** [comment]
Sorry but this is not enough information to provide any help. Please consider providing an example case and reproducible steps in the future.
