### ISSUE TITLE
Class not found when unmarshalling: net.rdrei.android.dirchooser.AutoParcel_DirectoryChooserConfig

### ISSUE THREAD

**Issue by ysqcn** [passy/Android-DirectoryChooser#95]
I import "library" content into my project, and when DirectoryChooserActivity is invoked, I can see the DriChooser UI and soon after it, the app is crashed with bellow stack dump.

Bellow is my code to use the library:
==============================
    private void dialogChooseWxDir() {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                final Intent chooserIntent = new Intent(
                        WXVExporterActivity.this,
                        DirectoryChooserActivity.class);

                final DirectoryChooserConfig config = DirectoryChooserConfig.builder()
                        .newDirectoryName("DirChooserSample")
                        .allowReadOnlyDirectory(false)
                        .allowNewDirectoryNameModification(false)
                        .build();

                chooserIntent.putExtra(
                        DirectoryChooserActivity.EXTRA_CONFIG,
                        config);

                startActivityForResult(chooserIntent, REQUEST_DIRECTORY);
            }
        });
    }

The stack dump:
==============================
I/InputDispatcher( 2362): Delivering touch to: action: 0x1
E/Parcel  ( 2362): Class not found when unmarshalling: net.rdrei.android.dirchooser.AutoParcel_DirectoryChooserConfig
E/Parcel  ( 2362): java.lang.ClassNotFoundException: net.rdrei.android.dirchooser.AutoParcel_DirectoryChooserConfig
E/Parcel  ( 2362):      at java.lang.Class.classForName(Native Method)
E/Parcel  ( 2362):      at java.lang.Class.forName(Class.java:204)
E/Parcel  ( 2362):      at java.lang.Class.forName(Class.java:169)
E/Parcel  ( 2362):      at android.os.Parcel.readParcelableCreator(Parcel.java:2091)
E/Parcel  ( 2362):      at android.os.Parcel.readParcelable(Parcel.java:2055)
E/Parcel  ( 2362):      at android.os.Parcel.readValue(Parcel.java:1971)
E/Parcel  ( 2362):      at android.os.Parcel.readMapInternal(Parcel.java:2255)
E/Parcel  ( 2362):      at android.os.Bundle.unparcel(Bundle.java:223)
E/Parcel  ( 2362):      at android.os.Bundle.getString(Bundle.java:1082)
E/Parcel  ( 2362):      at android.content.Intent.getStringExtra(Intent.java:4961)
E/Parcel  ( 2362):      at com.android.server.am.ActivityStack.startActivityLocked(ActivityStack.java:3761)
E/Parcel  ( 2362):      at com.android.server.am.ActivityStack.startActivityMayWait(ActivityStack.java:4977)
E/Parcel  ( 2362):      at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:3173)
E/Parcel  ( 2362):      at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:3129)
E/Parcel  ( 2362):      at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:157)
E/Parcel  ( 2362):      at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2125)
E/Parcel  ( 2362):      at android.os.Binder.execTransact(Binder.java:388)
E/Parcel  ( 2362):      at dalvik.system.NativeStart.run(Native Method)
E/Parcel  ( 2362): Caused by: java.lang.NoClassDefFoundError: net/rdrei/android/dirchooser/AutoParcel_DirectoryChooserConfig
E/Parcel  ( 2362):      ... 18 more
E/Parcel  ( 2362): Caused by: java.lang.ClassNotFoundException: Didn't find class "net.rdrei.android.dirchooser.AutoParcel_DirectoryChooserConfig" on path:
E/Parcel  ( 2362):      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:64)
E/Parcel  ( 2362):      at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
E/Parcel  ( 2362):      at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
E/Parcel  ( 2362):      ... 18 more
I/power   ( 2362): *** acquire_dvfs_lock : lockType : 1  freq : 1200000
D/SSRMv2:CustomFrequencyManagerService( 2362): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1200000  uid : 1000  pid : 2362  pkgName : ACTIVIT
_RESUME_BOOSTER@5
W/ActivityManager( 2362): mDVFSHelper.acquire()
D/dalvikvm( 2362): GC_FOR_ALLOC freed 1922K, 22% free 27690K/35368K, paused 89ms, total 89ms

**Comment by ysqcn** [comment]
Found it is same with issue #73 and I am using Android studio 2.1.1
The sample app cloned from project works fine in Android studio.

**Comment by ysqcn** [comment]
It looks it is cause by a "system.exit(0)" in my Activity onStop, by removing it, the issue is gone. Thanks!
